name: CI/CD - Student App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
          docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/student-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/student-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to EC2
        run: |
          echo "${{ secrets.AWS_KEY }}" > key.pem
          chmod 600 key.pem

          ssh -o StrictHostKeyChecking=no -i key.pem \
          ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            set -e

            echo "ðŸ”¹ Ensure Docker network exists"
            docker network create my_network || true

            echo "ðŸ”¹ Login to Docker Hub"
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            echo "ðŸ”¹ Pull latest image"
            docker pull ${{ secrets.DOCKER_USERNAME }}/student-app:latest

            echo "ðŸ”¹ Stop old container"
            docker stop student-app || true
            docker rm student-app || true

            echo "ðŸ”¹ Run new container"
            docker run -d \
              --name student-app \
              --network my_network \
              -p 5000:5000 \
              -e DB_HOST=db \
              -e DB_USER=root \
              -e DB_PASSWORD=root \
              -e DB_NAME=attendance_db \
              --restart always \
              ${{ secrets.DOCKER_USERNAME }}/student-app:latest

            echo "âœ… Deployment successful"
          EOF
