name: Deploy Student App (Blue-Green)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
          docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/student-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/student-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        run: |
          echo "${{ secrets.AWS_KEY }}" > key.pem
          chmod 600 key.pem

          ssh -o StrictHostKeyChecking=no -i key.pem \
          ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
          
          set -e

          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/student-app:latest

          # Determine active container
          if docker ps | grep student-app-blue; then
              ACTIVE=blue
              ACTIVE_PORT=5001
              IDLE=green
              IDLE_PORT=5002
          elif docker ps | grep student-app-green; then
              ACTIVE=green
              ACTIVE_PORT=5002
              IDLE=blue
              IDLE_PORT=5001
          else
              # First deploy
              ACTIVE=none
              ACTIVE_PORT=0
              IDLE=blue
              IDLE_PORT=5001
          fi

          echo "Deploying $IDLE container"

          # Run new container
          docker rm -f student-app-$IDLE || true
          docker run -d \
            --name student-app-$IDLE \
            --network my_network \
            -p $IDLE_PORT:5000 \
            -e DB_HOST=mysql-db \
            -e DB_USER=root \
            -e DB_PASSWORD=root \
            -e DB_NAME=attendance_db \
            --restart always \
            ${{ secrets.DOCKER_USERNAME }}/student-app:latest

          # Switch Nginx only if not first deploy
          if [ "$ACTIVE" != "none" ]; then
              sudo sed -i "s/127.0.0.1:$ACTIVE_PORT/127.0.0.1:$IDLE_PORT/" /etc/nginx/conf.d/student-app.conf
              sudo nginx -t
              sudo systemctl reload nginx

              # Stop old container
              docker rm -f student-app-$ACTIVE || true
          fi

          echo "âœ… Deployment complete"
          EOF
